version: "3.8"

services:
  # Backend service
  backend:
    build:
      context: ./claude-backend
    ports:
      - "5000:5000"
    volumes:
      - ./claude-backend:/app
      - /app/node_modules
      - ./claude-backend/.env:/app/.env
      - ./uploads:/app/uploads
    depends_on:
      - db
    env_file:
      - ./claude-backend/.env
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=claude_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./claude-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./claude-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
      - VITE_API_PREFIX=/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=claude_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
