version: "3.8"

services:
  # Backend service
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=claude_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=claude_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
